# Team Name: Team++
# Project 2: Config Makefile
# CMPS 111: Spring 2014

# CREATED (4-19-2014)

# Note: These rules remove the files at COPYDIR, replacing 
#       them with your own. Be careful!

# make -> Copies main.c to COPYDIR
# (Used for sanity check to make sure we get changes each compile).

COPYDIR = /usr/src/kernel

all:
	cp main.c $(COPYDIR)