# Team Name: Team++
# Project 2: Config Makefile
# CMPS 111: Spring 2014

# CREATED (4-27-2014)

# Note: These rules remove the files at COPYDIR, replacing 
#       them with your own. Be careful!

# make -> Copies schedule.c to COPYDIR

COPYDIR = /usr/src/servers/pm

all:
	cp schedule.c $(COPYDIR)
	cp utility.c $(COPYDIR)