# Team Name: Team++
# Project 2: Config Makefile
# CMPS 111: Spring 2014

# CREATED (4-19-2014)

# Note: These rules remove the files at COPYDIR, replacing 
#       them with your own. Be careful!

# make -> Copies config.h to COPYDIR

COPYDIR = /usr/include/minix

all:
	cp config.h $(COPYDIR)